### ISSUE TITLE
Not working in LightEdit mode

### ISSUE THREAD

**Issue by dima74** [mikinw/TabMover#2]
https://blog.jetbrains.com/idea/2020/04/lightedit-mode/

**Comment by mikinw** [comment]
To make it work would indeed be desirable.

**Comment by mikinw** [comment]
I've tried to check if this was possible, but it seems, the LightEdit mode is so lightweight, because a lot of features are not accessible. Eg. the plugins. I don't think this feature is possible currently. 
So I will close this issue. Sorry
