### ISSUE TITLE
The plugin is incompatible with 2023.1

### ISSUE THREAD

**Issue by Alexsey** [mikinw/TabMover#4]
Thank you for developing this awesome plugin! I'm using it for years, and hope there will be a way to continue using it in 2023 :) 2023.1 is already RC. Please, is it possible to make it compatible? Thank you

**Comment by mikinw** [comment]
@Alexsey thank you for your interest!
Using Jetbrain's plugin verifier, it tells me, the plugin is compatible with IntelliJ IDEA Ultimate IU-231.8109.90 (2023.1 (rc)). There are some deprecation warnings, but those don't effect compatibility. What makes you think the plugin is incompatible with 2023.1?

**Comment by Alexsey** [comment]
WebStorm is telling me that the plugin is not compatible with WebStorm 2023.1 RC
<img width="529" alt="Screenshot 2023-03-22 at 10 40 55" src="https://user-images.githubusercontent.com/6392013/226847434-8e06acd1-9fad-4075-a0d0-3cd60b9ae69d.png">

**Comment by Alexsey** [comment]
Ok, I think I know what the problem is - in the [build.gradle.kts](https://github.com/mikinw/TabMover/blob/master/build.gradle.kts#L39) you are having `untilBuild.set("223.*")` while **2023.1** are **231.***

So, if plugin viewer is showing you that there are no incompatibilities it means that all it takes to make TabMover compatible with 2023.1 is just to update the `build.gradle.kts` and re-publish the plugin

**Comment by alexanderankin** [comment]
wouldn't the correct solution be to remove the until entirely? wouldn't it be safer to assume the plugin is working, instead of issuing a new warning for every new intellij version?

**Comment by huybn5776** [comment]
For now,  the workaround is find plugin under JetBrain directory, open TabMover-1.5.0.jar as zip, modify /META-INF/plugin.xml, replace 223 to 231 than save it back.

**Comment by mikinw** [comment]
@Alexsey I see now (I've always used my builds directly copied to my intellij, so I've never seen this warning :-) )
Anyway. I've made a new build (v1.5.1), that only increases the max version number. This should solve the problem in the short run. 
@alexanderankin maybe you are right, but that field might be mandatory.

**Comment by Alexsey** [comment]
Thank you! I'll close the issue after the plugin is published so I would be able to verify that everything is good
