### ISSUE TITLE
The plugin is incompatible with 2023.2

### ISSUE THREAD

**Issue by ai212983** [mikinw/TabMover#7]
Hey guys.

IDEA 2023.2 is out now, look like the [same problem we had with 2023.1](https://github.com/mikinw/TabMover/issues/4).

There is [PR](https://github.com/mikinw/TabMover/pull/6) open to fix it.

**Comment by mikinw** [comment]
I've removed the "untilVersion" part from the manifest, so the 1.5.2 version should work for any new builds (no version bump would be needed hopefully). Though some Actions use deprecated API, so a new intellij version in the future might break the plugin again.
The plugin should have passed review in 2 business days.

**Comment by mikinw** [comment]
I've removed the "untilVersion" part from the manifest, so the 1.5.2 version should work for any new builds (no version bump would be needed hopefully). Though some Actions use deprecated API, so a new intellij version in the future might break the plugin again.
The plugin should have passed review in 2 business days.

**Comment by banagale** [comment]
Note in case someone else sees this, initially the new version may show that it is incompatible with the IDE.  But if you restart the IDE it seems fine.

<img width="434" alt="Screenshot 2023-08-11 at 9 04 33 AM" src="https://github.com/mikinw/TabMover/assets/1409710/5eb3364b-ed40-4ba1-a8f0-19232b244449">
